#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update

sudo apt-get install -y nginx

echo "<!DOCTYPE html><html><head><title>Hello World!</title></head>
<body><h1>Hello World!</h1></body></html>" | sudo tee /var/www/html/index.html

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;

        server_name _;

        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
