#!/usr/bin/env bash
# This script configures our Nginx server so that /redirect_me is redirecting to another page

sudo apt-get update

sudo apt-get install -y nginx

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

	location / {
        	root /var/www/html;
        	index index.html index.htm index.nginx-debian.html;
	}

        server_name _;

        location /redirect_me {
                return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
        }
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
