#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update

sudo apt-get install -y nginx

echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

	location / {
        	root /var/www/html;
        	index index.html index.htm index.nginx-debian.html;
	}

        server_name _;

        error_page 404 /404.html;
}" > /etc/nginx/sites-available/default'

sudo service nginx restart
