#!/usr/bin/env bash
# This script installs a nginx web server

sudo apt-get update

sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html

sudo bash -c 'echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;

	location / {
        	root /var/www/html;
        	index index.html index.htm index.nginx-debian.html;

		add_header X-Served-By: $(hostname);
	}

        server_name _;

}" > /etc/nginx/sites-available/default'

sudo service nginx restart
