#!/usr/bin/env bash
# This fixes the nginx configuration issue but keeps it short and sweet
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
kill "$(pgrep 'nginx' | head -1)"
