#!/usr/bin/env bash
# Fixes this container so that Nginx is running as the nginx user.
service_file_path="/lib/systemd/system/nginx.service"

sudo cp "$service_file_path" "$service_file_path.bak"

if ! service nginx stop; then
    echo "Failed to stop Nginx."
    exit 1
fi

sudo sed -i 's/ExecStartPre=\/usr\/sbin\/nginx -t -q -g '\''daemon on; master_process on;'\''/ExecStartPre=\/usr\/sbin\/nginx -t -q -g '\''user=nginx; daemon on; master_process on;'\''/g' "$service_file_path"

sudo sed -i 's/ExecStart=\/usr\/sbin\/nginx -g '\''daemon on; master_process on;'\''/ExecStart=\/usr\/sbin\/nginx -g '\''user=nginx; daemon on; master_process on;'\'' -c \/etc\/nginx\/nginx.conf/g' "$service_file_path"

sudo sed -i 's|ExecReload=/usr/sbin/nginx.*|ExecReload=/usr/sbin/nginx -g '\''user=nginx; daemon on; master_process on;'\'' -s reload|' "$service_file_path"

if ! grep -q '^\s*user' /etc/nginx/nginx.conf; then
    sed -i '1i user nginx;' /etc/nginx/nginx.conf
fi

sed -i 's/\(listen[[:space:]]\+\)80;/\18080;/' /etc/nginx/sites-available/default

sudo service nginx restart
