#!/usr/bin/env bash
# Fixes this container so that Nginx is running as the nginx user.
if ! service nginx stop; then
    echo "Failed to stop Nginx."
    exit 1
fi

if ! grep -q '^\s*user' /etc/nginx/nginx.conf; then
    sed -i '1i user nginx;' /etc/nginx/nginx.conf
fi

sed -i 's/\(listen[[:space:]]\+\)80;/\18080;/' /etc/nginx/sites-available/default
sudo service nginx restart
